language: python
python:
  - "pypy"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ||
          $TRAVIS_PYTHON_VERSION == '2.7' ||
          $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then
      pip install ./pies2overrides;
    fi
script:
  - pip install pytest
  - py.test
